### ISSUE TITLE
MPesaReversal Call not supporting Transaction Amount

### ISSUE THREAD

**Issue by jacques-iveri** [gabrieldwight/Mpesa-Sdk-Net#1]
The Mpesa Reversal call does not seem to support the transaction amount, which on the MPesa Deraja Portal is given as an important parameter value. 
It would therefore not generate the full json as one finds when you look at Safricoms Postman example collection:
{
    "Initiator": "",
    "SecurityCredential": "",
    "CommandID": "TransactionReversal",
    "TransactionID": "",
    **"Amount": "",**
    "ReceiverParty": "",
    "RecieverIdentifierType": "4",
    "ResultURL": "",
    "QueueTimeOutURL": "",
    "Remarks": "",
    "Occasion": ""
}

The fix to this would be the addition of this property to the MpesaResersal.cs class, and the addition of this as a parameter to the constructor of this class.

**Comment by gabrieldwight** [comment]
Hi, thanks for the issue. I will add the amount property and push an update.

**Comment by gabrieldwight** [comment]
Fixed in https://github.com/gabrieldwight/Mpesa-Sdk-Net/commit/02da08c16050a8c24b111abaf992e78331a49acd
